default_language_version:
  python: python3.9
default_stages: [commit, push]
exclude: ^.*\b(migrations)\b.*$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: check-yaml
    - id: debug-statements
    - id: check-ast
    - id: check-case-conflict
    - id: check-merge-conflict

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      additional_dependencies: [pyproject]

  - repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: [flake8-import-order==0.18.1]
