version: "3.9"

services:
  database:
    container_name: database
    image: postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    user: ${POSTGRES_USER}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 2s
      timeout: 2s
      retries: 5

  backend:
    container_name: backend
    build:
      context: .
      args:
        DEBUG: ${DEBUG:-False}
    volumes:
      - ${APP_LOCAL_VOLUME:-.}:${APP_CONTAINER_VOLUME:-/app}
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT:-8000}:8000
      - ${BACKEND_STATIC_PORT:-8001}:8001
    environment:
      - DEBUG=${DEBUG:-False}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      database:
        condition: service_healthy
