# Generated by Django 3.2.9 on 2022-02-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='players.player')),
            ],
            options={
                'unique_together': {('player_id', 'name')},
            },
        ),
    ]
